-- Smart Green House System V12 database schema
-- Run this in Supabase SQL Editor.

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  temperature double precision,
  humidity double precision,
  lux double precision,
  moisture_raw integer,
  moisture_percent integer,
  water_level_raw integer,
  water_level_percent integer,
  light_relay boolean default false,
  pump_relay boolean default false,
  tray_pump_relay boolean default false,
  fertilizer_relay boolean default false,
  light_on_seconds integer default 0,
  pump_on_seconds integer default 0,
  tray_pump_on_seconds integer default 0,
  fertilizer_on_seconds integer default 0
);

alter table public.sensor_readings add column if not exists water_level_raw integer;
alter table public.sensor_readings add column if not exists water_level_percent integer;
alter table public.sensor_readings add column if not exists tray_pump_relay boolean default false;
alter table public.sensor_readings add column if not exists fertilizer_relay boolean default false;
alter table public.sensor_readings add column if not exists light_on_seconds integer default 0;
alter table public.sensor_readings add column if not exists pump_on_seconds integer default 0;
alter table public.sensor_readings add column if not exists tray_pump_on_seconds integer default 0;
alter table public.sensor_readings add column if not exists fertilizer_on_seconds integer default 0;

create table if not exists public.device_controls (
  device_name text primary key,
  mode text not null default 'auto' check (mode in ('auto', 'manual')),
  target_state boolean not null default false,
  updated_at timestamp with time zone not null default now()
);

insert into public.device_controls (device_name, mode, target_state)
values
  ('light_bulb', 'auto', false),
  ('water_pump', 'auto', false),
  ('tray_pump', 'auto', false),
  ('fertilizer_pump', 'manual', false)
on conflict (device_name) do nothing;

create table if not exists public.device_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  device_name text not null,
  event_type text not null,
  duration_seconds integer default 0
);

create table if not exists public.system_alerts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  alert_type text not null,
  message text not null,
  severity text default 'warning'
);

alter table public.sensor_readings enable row level security;
alter table public.device_controls enable row level security;
alter table public.device_events enable row level security;
alter table public.system_alerts enable row level security;

drop policy if exists "Allow anon select sensor readings" on public.sensor_readings;
drop policy if exists "Allow anon insert sensor readings" on public.sensor_readings;
drop policy if exists "Allow anon select device controls" on public.device_controls;
drop policy if exists "Allow anon insert device controls" on public.device_controls;
drop policy if exists "Allow anon update device controls" on public.device_controls;
drop policy if exists "Allow anon select device events" on public.device_events;
drop policy if exists "Allow anon insert device events" on public.device_events;
drop policy if exists "Allow anon select system alerts" on public.system_alerts;
drop policy if exists "Allow anon insert system alerts" on public.system_alerts;

create policy "Allow anon select sensor readings" on public.sensor_readings for select to anon using (true);
create policy "Allow anon insert sensor readings" on public.sensor_readings for insert to anon with check (true);

create policy "Allow anon select device controls" on public.device_controls for select to anon using (true);
create policy "Allow anon insert device controls" on public.device_controls for insert to anon with check (true);
create policy "Allow anon update device controls" on public.device_controls for update to anon using (true) with check (true);

create policy "Allow anon select device events" on public.device_events for select to anon using (true);
create policy "Allow anon insert device events" on public.device_events for insert to anon with check (true);

create policy "Allow anon select system alerts" on public.system_alerts for select to anon using (true);
create policy "Allow anon insert system alerts" on public.system_alerts for insert to anon with check (true);

grant usage on schema public to anon;
grant select, insert on public.sensor_readings to anon;
grant select, insert, update on public.device_controls to anon;
grant select, insert on public.device_events to anon;
grant select, insert on public.system_alerts to anon;


-- =========================================================
-- App Users Table for Login / Sign Up
-- Demo/class project only: password is stored so it can be viewed in database.
-- For real production, use Supabase Auth or password hashing.
-- =========================================================

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  created_at timestamp with time zone not null default now(),
  last_login_at timestamp with time zone,
  login_count integer not null default 0
);

insert into public.app_users (username, password)
values ('admin', '12345678')
on conflict (username) do nothing;

alter table public.app_users enable row level security;

drop policy if exists "Allow anon select app users" on public.app_users;
drop policy if exists "Allow anon insert app users" on public.app_users;
drop policy if exists "Allow anon update app users" on public.app_users;

create policy "Allow anon select app users"
on public.app_users
for select
to anon
using (true);

create policy "Allow anon insert app users"
on public.app_users
for insert
to anon
with check (true);

create policy "Allow anon update app users"
on public.app_users
for update
to anon
using (true)
with check (true);

grant select, insert, update on public.app_users to anon;


-- =========================================================
-- User Adjustable Threshold Settings
-- Website saves threshold values here.
-- ESP32 can also read this table if you want hardware threshold control.
-- =========================================================

create table if not exists public.system_settings (
  setting_key text primary key,
  setting_value jsonb not null,
  updated_at timestamp with time zone not null default now()
);

insert into public.system_settings (setting_key, setting_value)
values (
  'thresholds',
  '{"light_lux":150,"moisture_percent":70,"tray_water_percent":0}'::jsonb
)
on conflict (setting_key) do nothing;

alter table public.system_settings enable row level security;

drop policy if exists "Allow anon select system settings" on public.system_settings;
drop policy if exists "Allow anon insert system settings" on public.system_settings;
drop policy if exists "Allow anon update system settings" on public.system_settings;

create policy "Allow anon select system settings"
on public.system_settings
for select
to anon
using (true);

create policy "Allow anon insert system settings"
on public.system_settings
for insert
to anon
with check (true);

create policy "Allow anon update system settings"
on public.system_settings
for update
to anon
using (true)
with check (true);

grant select, insert, update on public.system_settings to anon;


-- =========================================================
-- ESP32 Connected Threshold + Tray Pump Safety Update
-- Run this again if ESP32 cannot read threshold settings.
-- =========================================================

alter table public.sensor_readings add column if not exists tray_pump_relay boolean default false;
alter table public.sensor_readings add column if not exists tray_pump_on_seconds integer default 0;

insert into public.device_controls (device_name, mode, target_state)
values ('tray_pump', 'auto', false)
on conflict (device_name) do nothing;

create table if not exists public.system_settings (
  setting_key text primary key,
  setting_value jsonb not null,
  updated_at timestamp with time zone not null default now()
);

insert into public.system_settings (setting_key, setting_value)
values (
  'thresholds',
  '{"light_lux":150,"moisture_percent":70,"tray_water_percent":0}'::jsonb
)
on conflict (setting_key) do nothing;

alter table public.system_settings enable row level security;

drop policy if exists "Allow anon select system settings" on public.system_settings;
drop policy if exists "Allow anon insert system settings" on public.system_settings;
drop policy if exists "Allow anon update system settings" on public.system_settings;

create policy "Allow anon select system settings"
on public.system_settings
for select
to anon
using (true);

create policy "Allow anon insert system settings"
on public.system_settings
for insert
to anon
with check (true);

create policy "Allow anon update system settings"
on public.system_settings
for update
to anon
using (true)
with check (true);

grant select, insert, update on public.system_settings to anon;


-- =========================================================
-- Dual Soil Moisture Sensor Update
-- moisture_percent remains the overall average used for auto irrigation.
-- =========================================================

alter table public.sensor_readings add column if not exists moisture_1_raw integer;
alter table public.sensor_readings add column if not exists moisture_1_percent integer;
alter table public.sensor_readings add column if not exists moisture_2_raw integer;
alter table public.sensor_readings add column if not exists moisture_2_percent integer;

-- Force existing bad threshold values to be inside the allowed range.
update public.system_settings
set setting_value = jsonb_build_object(
  'light_lux', coalesce((setting_value->>'light_lux')::numeric, 150),
  'moisture_percent', least(100, greatest(0, coalesce((setting_value->>'moisture_percent')::numeric, 70))),
  'tray_water_percent', least(100, greatest(0, coalesce((setting_value->>'tray_water_percent')::numeric, 0)))
)
where setting_key = 'thresholds';
